name: module_terraform
on:
  workflow_call:
    inputs:
      Stage:
        required: true
        type: string
      Environment:
        required: true
        type: string
    outputs:
      TerraformOutput:
        value: ${{ jobs.Terraform.outputs.TerraformOutput }}
        
jobs:
  Validation:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Validate files structure
      run: |
        ENVIRONMENT=$(echo "${{ inputs.Environment }}" | tr '[:upper:]' '[:lower:]')
        STAGE=$(echo "${{ inputs.Stage }}" | tr '[:upper:]' '[:lower:]')
        required_files=(
          main.tf
          providers.tf
          backend.tf
          outputs.tf
          cicd.json
          variables.tf
          ./stages/$STAGE.json
          ./environments/$ENVIRONMENT.tfvars.json
          ./environments/$ENVIRONMENT.tf
        )
        for file in "${required_files[@]}"; do
          [[ -f "$file" ]] || { echo "❌ Missing required file: $file"; exit 1; }
        done
        echo "✅ All required files are present"